name: CI_DEVELOP
on:
  push:
    branches: [ "DEVELOP" ]
  pull_request:
    branches: [ "DEVELOP" ]
jobs:
 build:
  name: PrimeroJob
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Executando o STEP1
     run: |
       echo Esse processo carrega uma mensagem,
       echo basica para entender o workflow
       echo 
   - name: Ambiente
     run: echo Usando a Branch de DEVELOP
