# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI_DEVELOP

on:
  push:
    branches: [ "DEVELOP" ]
  pull_request:
    branches: [ "DEVELOP" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build with Java
      run: javac src/Main.java -d out
    - name: Run Java
      run: java -cp out Main
    - name: Mensagem de sucesso
      run: echo Deu Certo!
    - name: Ambiente
      run: echo Usando a Branch de DEVELOP
