name: Java CI_MAIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build with Java
      run: javac src/Main.java -d out
    - name: Run Java
      run: java -cp out Main
    - name: Mensagem de sucesso
      run: echo Deu Certo!
    - name: Ambiente
      run: echo Usando a Branch de MAIN
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4 
      with:
        image: sophiekumagai/dockerfile
        tags: v1, latest
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
